from processa_conteudo import criar_banco, processar_arquivo

criar_banco()

processar_arquivo("bitcoin.pdf")
processar_arquivo("CAP 1 VC INVESTIDOR.docx")
processar_arquivo("CAP 1.docx")
processar_arquivo("CAP 2 VC INVESTIDOR.docx")
processar_arquivo("CAP 2.docx")
processar_arquivo("CAP 3 VC INVESTIDOR.docx")
processar_arquivo("CAP 3.docx")
processar_arquivo("CAP 4 VC INVESTIDOR.docx")
processar_arquivo("CAP 4.docx")
processar_arquivo("CAP 5 VC INVESTIDOR.docx")
processar_arquivo("CAP 5.docx")
processar_arquivo("CAP 6 VC INVESTIDOR.docx")
processar_arquivo("CAP 6.docx")
processar_arquivo("CAP 7 VC INVESTIDOR.docx")
processar_arquivo("CAP 7.docx")
processar_arquivo("CAP 8 VC INVESTIDOR.docx")
processar_arquivo("CAP 8.docx")
processar_arquivo("CAP 9 VC INVESTIDOR.docx")
processar_arquivo("CAP 9.docx")
processar_arquivo("CAP 10 LIVRO VC INVESTIDOR.docx")
processar_arquivo("CAP 10.docx")
processar_arquivo("CAP 11 LIVRO VC INVESTIDOR.docx")
processar_arquivo("CAP 12 LIVRO VC INVESTIDOR.docx")
processar_arquivo("cap livro COMO VENCER A SINDROME DO BILHETE[1].docx")
processar_arquivo("CAP LIVRO O QUE FAZER QUANDO A BOLSA CAI[1].docx")
processar_arquivo("cap NÃO DEPENDA DO INSS[1].docx")
processar_arquivo("COMO SE APOSENTAR EM 10 ANOS.docx")
processar_arquivo("CURSO - LIVRO - ORDER BUMP Dominando a Análise de Ações.docx")
processar_arquivo("DINHEIRO - Os Segredos De Quem Tem-1.pdf")
processar_arquivo("E BOOK CONSTRUINDO UMA CARTEIRA BLINDADA.docx")
processar_arquivo("E BOOK DIVIDENDOS EM DÓLAR VERSÃO FINAL.docx")
processar_arquivo("e book INVESTINDO PARA A INDEPENDENCIA FINANCEIRA.docx")
processar_arquivo("e-book dominando a analise de ações eua.docx")
processar_arquivo("GUIA DO BY AND HOLD.docx")
processar_arquivo("Livro Bolsa (REVISADO)[1].pdf")
processar_arquivo("LIVRO DIAGRAMADO Rico-por-conta-própria.pdf")
processar_arquivo("LIVRO DIGITAL As Maiores Lições do Investidor por Conta Própria.pdf")
processar_arquivo("LIVRO VC INVESTIDOR AULAS SCRIPT.docx")
processar_arquivo("order bump ETFs NOS EUA como construir uma carteira solida.docx")
processar_arquivo("relatório de posicionamento.docx")
processar_arquivo("relatório inimigos do meu cliente ideal.docx")
processar_arquivo("AOVIVO10MILCOMDIVIDENDOSTODOSOSMESES.docx")
processar_arquivo("AOVIVO4257REAISCOMFUNDOSIMOBILIARIOS.docx")
processar_arquivo("AOVIVOCARTEIRADEDIVIDENDOS.docx")
processar_arquivo("AOVIVOCRISEDASTARIFASTRUMP.docx")
processar_arquivo("AOVIVODIVIDENDOSNOAUTOMÁTICO.docx")
processar_arquivo("AOVIVOINVESTIDORINTELIGENTE.docx")
processar_arquivo("AULAAOVIVO.docx")
processar_arquivo("AO VIVO.docx")
processar_arquivo("AOVIVO_APOSENTADORIA_MILIONÁRIA.docx")
processar_arquivo("AOVIVO_AS_AÇÕES_MAIS_BARATAS_DA_BOLSA.docx")
processar_arquivo("AOVIVO_BITCOIN.docx")
processar_arquivo("AOVIVO_EUA.docx")
processar_arquivo("AOVIVO_SEGUNDO_SALÁRIO_COM_DIVIDENDOS.docx")
processar_arquivo("AOVIVO_VIRADA_FINANCEIRA.docx")